name: hedieaty_kevin_sherif_20p9405
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.5
  path: ^1.8.3
  intl: ^0.18.1
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.0
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  image: ^4.5.0
  collection: ^1.17.0
  firebase_messaging: ^15.1.6
  mockito: ^5.4.5
  build_runner: ^2.4.14
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 # Add this line

flutter:
  uses-material-design: true
  assets:
    - lib/assets/default_profile.png
    - lib/assets/Hedieaty_icon.png

flutter_icons:
  android: true
  ios: false # Disable iOS as this is for Android only
  image_path: "lib/assets/Hedieaty_icon.png"
