class Event {
  final int? id; // Primary key, autogenerated
  final String name;
  final String date; // Store as a string (ISO format)
  final String? location;
  final String? description;
  final String userId; // Foreign key linking to a user's ID

  Event({
    this.id,
    required this.name,
    required this.date,
    this.location,
    this.description,
    required this.userId,
  });

  // Convert Event to a Map for SQLite
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'date': date,
      'location': location,
      'description': description,
      'userId': userId,
    };
  }

  // Create an Event from a Map
  factory Event.fromMap(Map<String, dynamic> map) {
    return Event(
      id: map['id'],
      name: map['name'],
      date: map['date'],
      location: map['location'],
      description: map['description'],
      userId: map['userId'],
    );
  }
}
