// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1cR1gXct5U2BRuzIKwhs_WS86twEFIVw',
    appId: '1:9016871080:web:a3dfdc9a494a57773d5a9d',
    messagingSenderId: '9016871080',
    projectId: 'hedieaty-73a4d',
    authDomain: 'hedieaty-73a4d.firebaseapp.com',
    databaseURL: 'https://hedieaty-73a4d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hedieaty-73a4d.firebasestorage.app',
    measurementId: 'G-SHZ6PR4VMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFNX-I44dOsO3LKtRCw6HCAeudE6s5KKk',
    appId: '1:9016871080:android:1de4685d7e74dded3d5a9d',
    messagingSenderId: '9016871080',
    projectId: 'hedieaty-73a4d',
    databaseURL: 'https://hedieaty-73a4d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hedieaty-73a4d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1cR1gXct5U2BRuzIKwhs_WS86twEFIVw',
    appId: '1:9016871080:web:91733d970572e3db3d5a9d',
    messagingSenderId: '9016871080',
    projectId: 'hedieaty-73a4d',
    authDomain: 'hedieaty-73a4d.firebaseapp.com',
    databaseURL: 'https://hedieaty-73a4d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hedieaty-73a4d.firebasestorage.app',
    measurementId: 'G-3B3QR6MFPJ',
  );
}